#!/bin/sh

set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/frontend.postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/frontend.postrm.mysql
    dbc_go typo3-dummy $@
fi


if [ "$1" = "purge" ]; then
	rm -f /etc/typo3-dummy/debian-db.php
	if which ucf >/dev/null 2>&1; then
		ucf --purge /etc/typo3-dummy/debian-db.php
	fi
fi

#DEBHELPER#
